
name: Multi-arch Docker Release

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
      version:
        description: 'Release version'
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,arm

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build per platform
        run: |
          platforms=("linux/amd64" "linux/arm64" "linux/arm/v7")
          for platform in ${platforms[@]}; do
            arch=${platform#*/}
            arch=${arch//\//-}
            docker buildx build \
              --platform $platform \
              --output type=oci,dest=./${{ inputs.image_name }}-${{ inputs.version }}-$arch.tar \
              -t ${{ inputs.image_name }}:${{ inputs.version }} .
          done

      - name: Compress artifacts
        run: |
          for f in *.tar; do
            gzip -9 $f
          done
          ls -lh *.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          files: |
            ${{ inputs.image_name }}-${{ inputs.version }}-*.tar.gz
